version: '3.1'

services:

  sensors:
    hostname: iasensors
    container_name: iasensors
    build:
      context: .
      dockerfile: Dockerfile.sensors 
    depends_on:
      - "insert"
      - "mosquitto"

  insert:
    hostname: iainsert
    container_name: iainsert
    build: 
      context: .
      dockerfile: Dockerfile.insert
    depends_on:
      - "influxdb"
      - "mosquitto"

  influxdb:
    hostname: iainflux
    container_name: iainflux
    image: influxdb:2.1-alpine
    ports:
      - '10086:8086'
    volumes:
      - $PWD/docker/influx/data:/var/lib/influxdb2
      - $PWD/docker/influx/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

  mosquitto:
    hostname: iamosquitto
    container_name: iamosquitto
    image: eclipse-mosquitto
    ports:
      - 10083:10083
    restart: unless-stopped
    volumes:
      - $PWD/docker/mosquitto/data/:/mosquitto/data
      - $PWD/docker/mosquitto/config/:/mosquitto/config
      - $PWD/docker/mosquitto/log/:/mosquitto/log

  grafana:
    container_name: iagrafana
    hostname: iagrafana
    image: grafana/grafana-oss:main
    ports:
      - 10003:3000
    volumes:
      - $PWD/docker/grafana/data/:/var/lib/grafana  
    depends_on:
      - "influxdb"