FROM alpine
COPY insert/ /insert/

# Install node
RUN apk add nodejs npm
RUN node --version
RUN npm --version

#install pm2
RUN npm install pm2 -g

# run node script
WORKDIR "/insert"
RUN pwd
RUN npm i
RUN ls -lah
CMD ["pm2-runtime", "app.js"]