FROM alpine
COPY model/ /model/

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 
RUN ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN python3 --version

#CD
WORKDIR "/model"

# install pip 
RUN pip3 install -r requirements.txt

# run script
RUN pwd
RUN ls -lah
