version: '3.1'

services:
  mosquitto:
    hostname: iamosquitto
    container_name: iamosquitto
    image: eclipse-mosquitto
    ports:
      - 10083:10083
    restart: unless-stopped
    volumes:
      - ./docker/mosquitto/data/:/mosquitto/data
      - ./docker/mosquitto/config/:/mosquitto/config
      - ./docker/mosquitto/log/:/mosquitto/log

  insert:
    hostname: iainsert
    container_name: iainsert
    build:
      context: .
      dockerfile: Dockerfile.insert
    depends_on:
      - "mosquitto"

  sensors:
    hostname: iasensors
    container_name: iasensors
    build:
      context: .
      dockerfile: Dockerfile.sensors
    depends_on:
      - "insert"
      - "mosquitto"

  grafana:
    container_name: iagrafana
    hostname: iagrafana
    image: grafana/grafana-oss:main
    ports:
      - 10003:3000
    volumes:
      - $PWD/docker/grafana/data/:/var/lib/grafana
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=${POSTGRES_HOST}
      - GF_DATABASE_NAME=${POSTGRES_NAME}
      - GF_DATABASE_USER=${POSTGRES_USER}
      - GF_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - GF_DATABASE_SSL_MODE=enable

  model:
    hostname: iapredict
    container_name: iapredict
    build:
      context: .
      dockerfile: Dockerfile.predict
    depends_on:
      - "sensors"
      - "mosquitto"
