version: '3.1'

services:

  sensors:
    hostname: iasensors
    container_name: iasensors
    build:
      context: .
      dockerfile: Dockerfile.sensors 
    depends_on:
      - "insert"

  insert:
    hostname: iainsert
    container_name: iainsert
    build: 
      context: .
      dockerfile: Dockerfile.insert
    depends_on:
      - "influxdb"

  influxdb:
    hostname: iainflux
    container_name: iainflux
    image: influxdb:latest
    ports:
      - '10086:8086'
    # volumes:
    #   - influxdb-storage:/var/lib/influxdb
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "admin" 
      DOCKER_INFLUXDB_INIT_ORG: "my-org" 
      DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "zizi"

  mosquitto:
    hostname: iamosquitto
    container_name: iamosquitto
    image: eclipse-mosquitto
    ports:
      - 10083:1883
      - 10883:8883
    restart: unless-stopped
    # volumes:
    #   - /Main/docker_data/mosquitto/data/:/mosquitto/data
    #   - /Main/docker_data/mosquitto/config/:/mosquitto/config
    #   - /Main/docker_data/mosquitto/log/:/mosquitto/log

  grafana:
    container_name: iagrafana
    hostname: iagrafana
    image: grafana/grafana-oss:main
    ports:
      - 10003:3000
    # volumes:
    #   - /Main/docker_data/grafana/data/:/var/lib/grafana